### PR TITLE
Add support for Arch Linux for MimeDetective::new()

### LINKED ISSUE #1: MimeDetective::new() returns error on Arch Linux
So on Arch Linux, I have the `file` package installed which provides `/usr/share/file/misc/magic.mgc`, but it seems mime-detective is expecting the file to be located at `/usr/share/misc/magic.mgc`. Any ideas on how to fix this aside from symlinking? Thanks!

### PR DESCRIPTION
**Pull request by cjbassi**
Closes #1

I'm still learning idiomatic rust so feel free to change anything.

### CODE REVIEW

**Comment by pepsighan** [comment]
@cjbassi Sorry for late reply. Thanks for the PR.

Checking for a distro name feels like a hack to me. Isn't there a better way to find all the paths where a magic file might be stored regardless of the distro?

**Comment by pepsighan** [comment]
Also, we'll need to consider the cross-platform aspects of this library. Currently, as it is now the code path `MimeDetective::new` won't work on Windows.

We could use `#[cfg]` for windows but a user might store their libs in a different location which defeats our purpose. So, I am inclining towards removal of `MimeDetective::new`, so that the users of non-Ubuntu systems are not caught offguard. 

Feel free to share your opinions if you have found a way to magically get all paths for all systems.

**Comment by cjbassi** [comment]
I agree it feels a little hacky. And the filepath discrepancy on Arch Linux is actually more due to the `file` package than Arch itself.

I checked the `file` manpage and it actually lays out the potential file locations nicely, so I guess we'll have to add these:

> The information identifying these files is read from the compiled magic file /usr/share/file/misc/magic.mgc, or the files in the directory /usr/share/file/misc/magic if the compiled file does not exist.  In addition, if $HOME/.magic.mgc or $HOME/.magic exists, it will be used in preference to the system magic files.

I guess the only question is whether to default to checking all of that, or only if the `/usr/share/misc/magic.mgc` doesn't exist, or only if the `file` package is installed, idk. Any thoughts on the best way to do that?

**Comment by pepsighan** [comment]
I am thinking of removing `MimeDetective::new` completely and let the user decide which magic file to use for themselves with `MimeDetective::load_databases`. This will make it more explicit.

In cases where an app uses this lib for cross-platform usage, then they may do so by providing a local magic file themselves.
```
- project
  - app.exe
  - mymagic.mgc
```

**Comment by cjbassi** [comment]
Does windows have magic files too? It seems like macOS does, although the filepath is slightly different once again: https://ss64.com/osx/file.html. But that shouldn't be hard to add.

Hmm, I personally think it would be good to keep the `MimeDetective::new()` function. Is there any issues with adding the functionality as described by the `file` manpages for Linux and macOS? Forcing applications to include a magic file doesn't seem right imo, partly because it seems like they should be using the one provided by the distro. So you just end up forcing applications to implement their own version of `MimeDetective::new()`.

**Comment by pepsighan** [comment]
> Does windows have magic files too?

Yes you can install them.

> Is there any issues with adding the functionality as described by the `file` manpages for Linux and macOS?

There is no single Linux distro that a solution can be normalized to. Suppose today we add magic files for Arch Linux, tomorrow there is another distro which has its own unique file path, next day some more. And what for? For some magic function `MimeDetective::new` which may or may not work for a particular user.

Also, it's just a `MimeDetective::load_databases(&["/usr/share/misc/magic.mgc"]);` instead of `MimeDetective::new()` which could be tailored to your use case. I don't think it is that hard to write a few more characters/lines when you can get that much more flexibility.

**Comment by cjbassi** [comment]
> Suppose today we add magic files for Arch Linux, tomorrow there is another distro which has its own unique file path, next day some more.

So either this crate will handle adding support for different distros, or all the applications depending on this crate will have to individually.

> And what for? For some magic function `MimeDetective::new` which may or may not work for a particular user.

If it doesn't work for a user then we fix it.

> Also, it's just a `MimeDetective::load_databases(&["/usr/share/misc/magic.mgc"]);` instead of `MimeDetective::new()` which could be tailored to your use case. I don't think it is that hard to write a few more characters/lines when you can get that much more flexibility.

This is why we should keep both `load_databases` and `new` and let users pick which one they want. Perfect example of providing customization vs providing sane defaults.

For context, I'm currently working on https://github.com/kamiyaa/joshuto and we need the `new` function, since its a cross distro / cross platform application. So either way I'm going to have to write it :smile: And maybe someone else would like to use the implementation too.

**Comment by pepsighan** [comment]
> If it doesn't work for a user then we fix it.

We should not write erroneous code.

> all the applications depending on this crate will have to individually.

Maintaining flexibility & correctness is of the utmost importance. So, will remove `new`. If the apps desire cross-platform compatibility:
1. Either they embed `.mgc` within their program (simple).
2. Or write cases for each OS themselves.

Closing this PR as this is not the path to go forward.

**Pull request closed without merging**
